name: di_habitalink
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Dependencias para el mapa interactivo
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Esta es la sección importante.
flutter:
  uses-material-design: true

  # --- ESTA ES LA PARTE NUEVA Y DIFERENTE ---
  # En lugar de 'assets/', forzamos las carpetas hijas
  assets:
    - assets/engels_volkers/ref_w02uxx4/
    - assets/engels_volkers/ref_w02zvw0/
    - assets/logo/LogoSinFondo.png